- name: Configure local server
  hosts: webservers
  become: yes

  vars:
    app_name: appops-demo
    env: prod

  tasks:
    - name: Install nginx 
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy application
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
